### PR TITLE
Labels for por_PTpre1990

### PR DESCRIPTION
**Pull request by hectoralos**
Labels for por_PTpre1990 + several names for variants in Occitan, Sardinian and Italian

### CODE REVIEW

**Review by sushain97 — CHANGES_REQUESTED** [review]
You'll want to open a PR that changes https://github.com/apertium/apertium-apy/blob/master/language_names/variants.tsv rather than adding a new file like this one does. Unfortunately a new file wouldn't be included in the APIs responses. Also, I have some concerns about language names that are this long... I suspect they won't render very well at all.

**Comment by hectoralos** [comment]
Thanks for your feedback. What would you suggest for "European Portuguese (traditional spelling)"?

**Comment by sushain97** [comment]
What if we dropped the `traditional` bit?

**Comment by sushain97** [comment]
Now that I give it a second thought though, maybe what we should do is make it so that the frontend supports multi-word language names a bit better. For example, it'll truncate so that the name fits and then show the full name as a tooltip if you hover.

**Comment by jonorthwash** [comment]
@sushain97, sounds like a new issue to file against html-tools?

**Comment by sushain97** [comment]
Yep. I'd want to actually verify how it breaks and get a screenshot for that issue.

**Comment by hectoralos** [comment]
PR #164 substitutes this one. I'll close this one after you finish the discussion (or you can close it).

**Pull request closed without merging**
