### PR TITLE
+ frp in French

### PR DESCRIPTION
**Pull request by hectoralos**

### CODE REVIEW

**Review by sushain97 — APPROVED** [review]

**Comment by hectoralos** [comment]
Despite this merge in Beta you will still see the label "frp" instead of "Francoprovençal" if we choose the French interface. Is there anything wrong anywhere? (The same happens with the Arpitan interface, which still is not available)

**Comment by jonorthwash** [comment]
I think someone (@TinoDidriksen) will have to update the website for that to change.  Did you try it locally?

**Comment by hectoralos** [comment]
I'm sorry, I don't have any idea how to try this locally.

**Comment by TinoDidriksen** [comment]
The beta site's html-tools are not automatically updated (which is an oversight). I've cleaned and rebuilt it, and now the labels look ok to me: https://beta.apertium.org/index.fra.html?dir=frp-fra

**Comment by hectoralos** [comment]
Thanks a lot, @TinoDidriksen . The French labels are good, but for some reason the Arpitan version of the site is not yet available ( https://github.com/apertium/apertium-html-tools/pull/385 ). Maybe apertium-html-tools hasn't been automatically updated too.

**Pull request merged**
