### PR TITLE
Support 'prefs' in /translateDoc

### PR DESCRIPTION
**Pull request by unhammer**
Seems to work.

(Also started on translatePage, but need to sort out caching there, will do a later PR)

Cf. https://github.com/apertium/apertium-apy/issues/200

### CODE REVIEW

**Comment by unhammer** [comment]
```
Run NONPAIRS=/tmp/languages pipenv run make test
flake8 *.py apertium_apy/ language_names/ tests/
/bin/sh: 1: flake8: not found
make: *** [Makefile:17: test] Error 127
Error: Process completed with exit code 2.

```

**Comment by xavivars** [comment]
@sushain97, it seems an issue with python matrix & flake8

**Comment by sushain97** [comment]
Oh no! I'll take a look tonight. Thanks for the ping.

**Comment by sushain97** [comment]
@unhammer @xavivars rebased this branch on some fixes I landed on `master`. Looks much better now!

**Pull request merged**
