### PR TITLE
Add support for configuration files

### LINKED ISSUE #5: Use config file instead of long command line arguments
An argument like `--config=config.conf` would be great, the commands become really long with all the settings.

### PR DESCRIPTION
**Pull request by svineet**
New clean PR

Fixed #5

### CODE REVIEW

**Comment by svineet** [comment]
Can we get this merged? I was about to write docs for this but I don't want to confuse new users who won't find this capability after cloning, so I don't want to write docs before this is merged. Same for the suggestions PR.

**Comment by svineet** [comment]
Merge conflicts resolved, let's merge! :smile:

**Comment by jonorthwash** [comment]
Has this functionality been integrated already (e.g., it was merged in with another PR?)?

**Comment by svineet** [comment]
Doesn't look like it made it to trunk. I can resolve conflicts and fix anything that needs fixing, what do you think?

**Comment by jonorthwash** [comment]
Sounds good :)

**Comment by jonorthwash** [comment]
@svineet you going to be back for GCI to finish this off, or should I add it as a task for someone else to do?

**Comment by svineet** [comment]
Hey @jonorthwash, I will not be able to participate in GCI because of academic load (final exams start Dec 10), so you can add the task.

**Comment by Androbin** [comment]
Anyone still working on this?

**Comment by Androbin** [comment]
@jonorthwash Do we still want to merge this? Cause then I'd resolve the merge conflicts.

**Comment by jonorthwash** [comment]
It would be great for this to be finished, yeah.

**Pull request closed without merging**
