### PR TITLE
Upgrading flake8 version whilst fixing style issues it's complaining about

### PR DESCRIPTION
**Pull request by milanandreew**
Question: Is it OK if I just ignore W504?

### CODE REVIEW

**Comment by milanandreew** [comment]
I'll just ignore W504.

**Comment by sushain97** [comment]
Not unless there's a good reason to.

**Comment by milanandreew** [comment]
Well, it is just a linebreak error, but it still shows up after i fixed it, so i doubt it.

**Comment by sushain97** [comment]
Have you tried using `flake8` locally?

**Comment by milanandreew** [comment]
Yep.

**Comment by sushain97** [comment]
Ahh, I think you have to ignore one of them since they're contradictory. So go ahead and ignore the one that allows for the smallest diff.

**Comment by milanandreew** [comment]
OK.

**Comment by sushain97** [comment]
Thanks for taking care of this!

**Pull request merged**
