### PR TITLE
Arpitan

### PR DESCRIPTION
**Pull request by hectoralos**
Language names in Arpitan + Name of the Arpitan/Francoprovençal language in several languages

### CODE REVIEW

**Review by sushain97 — APPROVED** [review]
I would love it if you could sort your additions into the existing file but regardless, thank you!

**Review by sushain97 — COMMENTED** [review]
Er small nit, I believe these likely belong in `manual-additions.tsv`, not `manual-fixes.tsv`.

**Comment by hectoralos** [comment]
I couldn't understand what goes in manual-additions.tsv and what in manual-fixes.tsv. The language names in Aragonese are in this file, while the ones in Silesian are in the other. I translated from Aragonese.
So, should I change anything, since you approved the merge?

**Comment by sushain97** [comment]
There's some documentation about what belongs where in the README: https://github.com/apertium/apertium-apy/tree/master/language_names#language-names

**Pull request closed without merging**
